################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= skeleton
# CUDA source files (compiled with cudacc)
CUFILES		:= postprocessmain.cu skeleton.cu


################################################################################
# Rules and targets

include ../common.mk

